# Generated by Django 2.0.2 on 2018-02-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='member_count',
        ),
    ]
