# Generated by Django 2.0.2 on 2018-02-17 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0002_remove_account_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_leader', to='chama.Member'),
        ),
    ]
