# Generated by Django 2.0.2 on 2018-02-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0003_auto_20180217_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
